### ISSUE TITLE
DatastoreIO: IllegalArgumentException when doing initial splits

### ISSUE THREAD

**Issue by davorbonaci** [GoogleCloudPlatform/DataflowJavaSDK#101]
Datastore connector may throw an exception when doing initial splits. We should catch it and handle it gracefully, given that this is an optional optimization. 

    (4e1bbdfd880a21c1): java.lang.IllegalArgumentException: Query cannot have any inequality filters.

See [StackOverflow](http://stackoverflow.com/questions/34956283/query-cannot-have-any-inequality-filters) for more information.

**Comment by sanderploegsma** [comment]
I'm still seeing this issue in version 2.1.0:

```
java.lang.IllegalArgumentException: Query cannot have any inequality filters.
        at com.google.datastore.v1.client.QuerySplitterImpl.validateFilter(QuerySplitterImpl.java:104)
        at com.google.datastore.v1.client.QuerySplitterImpl.validateQuery(QuerySplitterImpl.java:127)
        at com.google.datastore.v1.client.QuerySplitterImpl.getSplits(QuerySplitterImpl.java:64)
        at org.apache.beam.sdk.io.gcp.datastore.DatastoreV1$Read.splitQuery(DatastoreV1.java:419)
        at org.apache.beam.sdk.io.gcp.datastore.DatastoreV1$Read.access$100(DatastoreV1.java:255)
        at org.apache.beam.sdk.io.gcp.datastore.DatastoreV1$Read$SplitQueryFn.processElement(DatastoreV1.java:808)
        at org.apache.beam.sdk.io.gcp.datastore.DatastoreV1$Read$SplitQueryFn$DoFnInvoker.invokeProcessElement(Unknown Source)
        at org.apache.beam.runners.direct.repackaged.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:177)
        at org.apache.beam.runners.direct.repackaged.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:141)
        at org.apache.beam.runners.direct.repackaged.runners.core.SimplePushbackSideInputDoFnRunner.processElementInReadyWindows(SimplePushbackSideInputDoFnRunner.java:70)
        at org.apache.beam.runners.direct.ParDoEvaluator.processElement(ParDoEvaluator.java:182)
        at org.apache.beam.runners.direct.DoFnLifecycleManagerRemovingTransformEvaluator.processElement(DoFnLifecycleManagerRemovingTransformEvaluator.java:51)
        at org.apache.beam.runners.direct.TransformExecutor.processElements(TransformExecutor.java:146)
        at org.apache.beam.runners.direct.TransformExecutor.run(TransformExecutor.java:110)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

This is using a very simple query:

``` java
PCollection<Entity> getEntities(Pipeline pipeline, String kind, DataflowPipelineOptions options) {
    Date startDate = Date.from(LocalDate.of(2017, 5, 20).atTime(16, 49).toInstant(ZoneOffset.UTC));

    Query query = Query
        .newBuilder()
        .addKind(KindExpression.newBuilder().setName("User").build())
        .setFilter(DatastoreHelper.makeFilter("registeredDate", PropertyFilter.Operator.GREATER_THAN_OR_EQUAL, DatastoreHelper.makeValue(startDate)))
        .build();

    return pipeline.apply("Read " + kind, DatastoreIO.v1().read().withProjectId(options.getProject()).withQuery(query));
}
```

**Comment by KarthikaRamani** [comment]
Hi I am still getting this issue, java.lang.IllegalArgumentException: Query cannot have any inequality filters. i am using 2.3.0 version
