### ISSUE TITLE
Starting a job with JDK >=1.8.0_72 fails with SSL exception:

### ISSUE THREAD

**Issue by derjust** [GoogleCloudPlatform/DataflowJavaSDK#122]
Trying to start a dataflow job via `BlockingDataflowPipelineRunner` on Oracle JDK `1.8.0_72` or `1.8.0_73` fails with the following exception using the Dataflow SDK `1.4.0`:

```
Exception in thread "main" java.lang.RuntimeException: Failed to construct instance from factory method BlockingDataflowPipelineRunner#fromOptions(interface com.google.cloud.dataflow.sdk.options.PipelineOptions)
	at com.google.cloud.dataflow.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:233)
	at com.google.cloud.dataflow.sdk.util.InstanceBuilder.build(InstanceBuilder.java:162)
	at com.google.cloud.dataflow.sdk.runners.PipelineRunner.fromOptions(PipelineRunner.java:57)
	at com.google.cloud.dataflow.sdk.Pipeline.create(Pipeline.java:134)
	at com.sungard.advtech.bigtable_df.theREALstuff.IngestionPipeline.main(IngestionPipeline.java:145)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.cloud.dataflow.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:222)
	... 4 more
Caused by: java.lang.IllegalAccessError: tried to access field sun.security.ssl.Handshaker.localSupportedSignAlgs from class sun.security.ssl.ClientHandshaker
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:281)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:384)
	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
	at com.google.cloud.hadoop.util.ChainingHttpRequestInitializer$2.intercept(ChainingHttpRequestInitializer.java:98)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.hadoop.util.ResilientOperation$AbstractGoogleClientRequestExecutor.call(ResilientOperation.java:166)
	at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:66)
	at com.google.cloud.dataflow.sdk.util.GcsUtil.bucketExists(GcsUtil.java:310)
	at com.google.cloud.dataflow.sdk.util.GcsUtil.bucketExists(GcsUtil.java:297)
	at com.google.cloud.dataflow.sdk.util.DataflowPathValidator.verifyPathIsAccessible(DataflowPathValidator.java:79)
	at com.google.cloud.dataflow.sdk.util.DataflowPathValidator.validateOutputFilePrefixSupported(DataflowPathValidator.java:62)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.fromOptions(DataflowPipelineRunner.java:185)
	at com.google.cloud.dataflow.sdk.runners.BlockingDataflowPipelineRunner.fromOptions(BlockingDataflowPipelineRunner.java:82)
	... 9 more
```

With Oracle JDK `1.8.0_40` it's working like a charm. We haven't tested release versions in between.
This behavior happens on OSX and Linux.

**Comment by davorbonaci** [comment]
Hi Sebastian,
thanks for this report -- we are investigating.

**Comment by davorbonaci** [comment]
On a quick glance, this doesn't appear to be an issue in Dataflow SDK. It seems like the exception is due to a JRE class trying to access a field of another JRE class.

We are investigating further. In the meanwhile, we suggest using the previous JDK.

**Comment by derjust** [comment]
From the [BT connector](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/) we inherited the ALPN version/depenendency.

With a wider range of recognized ALPN versions it's working with more recent versions of the JDK. Something like this:
```xml

		<profile>
			<id>1.8.0u51</id>
			<activation>
				<jdk>1.8.0.51</jdk>
			</activation>
			<properties>
				<alpn.version>8.1.4.v20150727</alpn.version>
			</properties>
		</profile>
		<profile>
			<id>1.8.0u60</id>
			<activation>
				<jdk>1.8.0.60</jdk>
			</activation>
			<properties>
				<alpn.version>8.1.5.v20150921</alpn.version>
			</properties>
		</profile>
		<profile>
			<id>1.8.0u65-1.8.0u66</id>
			<activation>
				<jdk>[1.8.0.65,1.8.0u66]</jdk>
			</activation>
			<properties>
				<alpn.version>8.1.6.v20151105</alpn.version>
			</properties>
		</profile>
		<profile>
			<id>1.8.0u71-1.8.0u74</id>
			<activation>
				<jdk>[1.8.0.71,1.8.0u74]</jdk>
			</activation>
			<properties>
				<alpn.version>8.1.7.v20160121</alpn.version>
			</properties>
		</profile>
```

**Comment by davorbonaci** [comment]
Thanks Sebastian for figuring this out.
