### ISSUE TITLE
BigTableIO is not supported in Streaming mode

### ISSUE THREAD

**Issue by ankurcha** [GoogleCloudPlatform/DataflowJavaSDK#148]
The class `com.google.cloud.dataflow.sdk.io.bigtable.BigtableIO.Write` is currently implemented using  `Sink`. This means that they may only be used in batch mode. It would be nice to have it implemented in a way to support streaming mode too.

An exception to that effect is:

```bash
java.lang.UnsupportedOperationException: The Write transform is not supported by the Dataflow streaming runner.
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner$StreamingWrite.apply(DataflowPipelineRunner.java:2271)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner$StreamingWrite.apply(DataflowPipelineRunner.java:2262)
	at com.google.cloud.dataflow.sdk.runners.PipelineRunner.apply(PipelineRunner.java:74)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.apply(DataflowPipelineRunner.java:413)
	at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:367)
	at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:274)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.apply(DataflowPipelineRunner.java:411)
	at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:367)
	at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:274)
	at com.google.cloud.dataflow.sdk.values.PCollection.apply(PCollection.java:161)
	at com.google.cloud.dataflow.sdk.io.bigtable.BigtableIO$Write.apply(BigtableIO.java:401)
	at com.google.cloud.dataflow.sdk.io.bigtable.BigtableIO$Write.apply(BigtableIO.java:325)
	at com.google.cloud.dataflow.sdk.runners.PipelineRunner.apply(PipelineRunner.java:74)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.apply(DataflowPipelineRunner.java:413)
	at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:367)
	at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:290)
	at com.google.cloud.dataflow.sdk.values.PCollection.apply(PCollection.java:174)
	at com.brightcove.rna.transforms.PersistToBigTable.apply(PersistToBigTable.java:33)
	at com.brightcove.rna.transforms.PersistToBigTable.apply(PersistToBigTable.java:12)
	at com.google.cloud.dataflow.sdk.runners.PipelineRunner.apply(PipelineRunner.java:74)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.apply(DataflowPipelineRunner.java:413)
	at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:367)
	at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:290)
	at com.google.cloud.dataflow.sdk.values.PCollection.apply(PCollection.java:174)
	at com.brightcove.rna.transforms.AnalyticsTransform.apply(AnalyticsTransform.java:35)
	at com.brightcove.rna.transforms.AnalyticsTransform.apply(AnalyticsTransform.java:12)
	at com.google.cloud.dataflow.sdk.runners.PipelineRunner.apply(PipelineRunner.java:74)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.apply(DataflowPipelineRunner.java:413)
	at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:367)
	at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:274)
	at com.google.cloud.dataflow.sdk.values.PCollection.apply(PCollection.java:161)
	at com.brightcove.rna.pipeline.AnalyticsPipeline.run(AnalyticsPipeline.java:38)
	at com.brightcove.rna.pipeline.MainExecutor$PipelineExecutionType.lambda$static$6(MainExecutor.java:32)
	at com.brightcove.rna.pipeline.MainExecutor.run(MainExecutor.java:21)
	at com.brightcove.rna.Main.main(Main.java:25)
E
```

**Comment by davorbonaci** [comment]
Thanks Ankur. Indeed, this is the case currently.

There's a different connector; a hbase-based one [here](https://cloud.google.com/bigtable/docs/dataflow-hbase), which is maintained outside the mainline Dataflow SDK. You can use this connector to write an unbounded `PCollection` to Google Cloud Bigtable.

**Comment by ankurcha** [comment]
Are there any significant advantages with in using BigTableIO vs the HBase connector? From what I can tell dealing directly in the protos is much "lighter" than going through the abstractions for HBase. Also, it avoids getting yet another source of transitive dependencies.

**Comment by davorbonaci** [comment]
You are exactly right! Those are the major differences.

**Comment by ankurcha** [comment]
Any updates on this?

**Comment by dhalperi** [comment]
Hi Ankur,

We are currently tracking this issue on Apache Beam JIRA: https://issues.apache.org/jira/browse/BEAM-46

The update is that someone has started working on it -- @ianzhou1.

Thanks,
Dan
