### ISSUE TITLE
no translator registered for GroupByKey.GroupByKeyOnly

### ISSUE THREAD

**Issue by crackercracked** [GoogleCloudPlatform/DataflowJavaSDK#169]
Hi sorry not sure whether it is a right place to post question but running into this error when trying to do GoGroupByKey 
as

```
PCollection<KV<String, TableRow>> pt1 = ...;
    PCollection<KV<String, MyClass>> pt2 = ...;
    final TupleTag<TableRow> t1 = new TupleTag<>();
    final TupleTag<MyClass> t2 = new TupleTag<>();
    PCollection<KV<String, CoGbkResult>> coGbkResultCollection =
    KeyedPCollectionTuple.of(t1, pt1)
                     .and(t2, pt2)
                     .apply(CoGroupByKey.<String>create());
```

Due to no translator registered to DataflowPipelineRunner

**Comment by dhalperi** [comment]
Hi @crackercracked, can you please provide a stack trace?

**Comment by crackercracked** [comment]
sure! as follows:
```
Exception in thread "main" java.lang.IllegalStateException: no translator registered for GroupByKey.GroupByKeyOnly
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineTranslator$Translator.visitTransform(DataflowPipelineTranslator.java:500)
	at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:219)
	at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:215)
	at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:215)
	at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:215)
	at com.google.cloud.dataflow.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:102)
	at com.google.cloud.dataflow.sdk.Pipeline.traverseTopologically(Pipeline.java:259)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineTranslator$Translator.translate(DataflowPipelineTranslator.java:455)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineTranslator.translate(DataflowPipelineTranslator.java:146)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.run(DataflowPipelineRunner.java:325)
	at com.google.cloud.dataflow.sdk.runners.BlockingDataflowPipelineRunner.run(BlockingDataflowPipelineRunner.java:95)
	at exposure.mb.ExposureGenerationPipeline.runPipeline(MyPipeline.java:271)
	at exposure.mb.ExposureGenerationPipeline.main(MyPipeline.java:326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by crackercracked** [comment]
btw just by peeking at source code, it seems that it is because GroupByKeyOnly class is not registered in `DataflowPipelineTranslator.java`? btw i am confused how `CoGroupByKey` became `GroupByKeyOnly` class after retrieving from `TransformTreeNode`

**Comment by bjchambers** [comment]
Can you post details about the actual example you're running?

The lack of translator for `GroupByKeyOnly` is intentional -- it is a primitive implemented by the Dataflow service. The strange part here is that running a pipeline shouldn't lead to a `GroupByKeyOnly` being exposed to the translator.

None of our tests for `CoGroupByKeyOnly` run into this, nor does the example in the docs, so we'd like to see more of your pipeline to see if something else is happening which is causing problems.

**Comment by lukecwik** [comment]
There was a recent question on SO with the same issue: http://stackoverflow.com/questions/36190192/no-translator-registered-for-groupbykey-groupbykeyonly/38153908#38153908

GroupByKeyOnly should have never appeared in the set of transforms applied to the graph for the DataflowPipelineRunner and this can happen because the pipeline may have been constructed without the runner being set on PipelineOptions followed by a call to [Blocking]DataflowPipelineRunner.run(Pipeline). The expected pattern is to not use the DataflowPipeline/DataflowPipelineRunner methods directly, for example:

```
PipelineOptions options = PipelineOptionsFactory.fromArgs(args);
// Make sure that runner is set before calling Pipeline.create(options)
Pipeline p = Pipeline.create(options);`

// Apply all your transforms
p.apply(... transforms ...);

PipelineResult result = p.run();
```

With the above example, you will be able to swap runners by adjusting the command line parameters to your application. For example, using the BlockingDataflowPipelineRunner will ensure that job result will have reached a terminal state before returning from p.run().

**Comment by dhalperi** [comment]
Closing as obsolete.
