### ISSUE TITLE
Write transform unsuitable for batched flows that use window functions.

### ISSUE THREAD

**Issue by benjumanji** [GoogleCloudPlatform/DataflowJavaSDK#27]
To reproduce, create any batch pipeline that uses a windowing function and any output method that uses `Write` to write the data out. The write results are output without a timestamp, ultimately causing an exception to be thrown.

```
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: WindowFn attemped to access input timestamp when none was available
	at com.google.cloud.dataflow.sdk.util.DoFnRunner$DoFnContext.makeWindowedValue(DoFnRunner.java:298)
	at com.google.cloud.dataflow.sdk.util.DoFnRunner$DoFnContext.outputWindowedValue(DoFnRunner.java:309)
	at com.google.cloud.dataflow.sdk.util.DoFnRunner$DoFnContext.output(DoFnRunner.java:351)
	at com.google.cloud.dataflow.sdk.transforms.Write$Bound$2.finishBundle(Write.java:180)
```

This unfortunate and prevents a lot of reuse of pipeline components. Fixing it would also have the added benefit of making the transform suitable for streaming (I think).

The difficulty here is of course, what timestamp should the the write result have? I think the current processing time would work just fine, and ultimately I don't think it really matters as it isn't used anywhere.

Thoughts? Feelings?

Ultimately I can work around this by either a) not using Write for anything b) in batch mode explicitly reifying timestamps into grouping keys and dropping windowing from all batch processing. a) is definitely more palatable than b), but I would prefer a third path.

**Comment by davorbonaci** [comment]
Hi Benjamin,
We concur this behavior is non-ideal. We are investigating a couple of different options and will reply back shortly.

**Comment by davorbonaci** [comment]
We have addressed this. `Write` should now be compatible with windowing without any new requirements or impact to user's code.

Please let us know if you see any additional issues. Thanks!

**Comment by benjumanji** [comment]
I'll have a play, thanks!
