### ISSUE TITLE
Error Trying to publish dataflow job

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/DataflowJavaSDK#272]
May 17, 2016 5:42:39 PM com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner fromOptions
INFO: PipelineOptions.filesToStage was not specified. Defaulting to files from the classpath: will stage 1 files. Enable logging at DEBUG level to see which files will be staged.
May 17, 2016 5:42:40 PM com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner run
INFO: Executing pipeline on the Dataflow Service, which will have billing implications related to Google Compute Engine usage and other Google Cloud Services.
May 17, 2016 5:42:40 PM com.google.cloud.dataflow.sdk.util.PackageUtil stageClasspathElements
INFO: Uploading 1 files from PipelineOptions.filesToStage to staging location to prepare for execution.
May 17, 2016 5:42:40 PM com.google.cloud.dataflow.sdk.util.PackageUtil stageClasspathElements
INFO: Uploading PipelineOptions.filesToStage complete: 0 files newly uploaded, 1 files cached
Dataflow SDK version: 1.2.1
May 17, 2016 5:42:42 PM com.google.cloud.dataflow.sdk.util.RetryHttpRequestInitializer$LoggingHttpBackoffUnsuccessfulResponseHandler handleResponse
WARNING: Request failed with code 400, will NOT retry: https://dataflow.googleapis.com/v1b3/projects/semtable/jobs
Exception in thread "main" java.lang.RuntimeException: Failed to create a workflow job: (1b9bcb283154c189): The workflow could not be created. Please try again in a few minutes. If you are still unable to create a job please contact customer support. Causes: (1b9bcb283154cdb2): An internal service error occurred. Please contact customer support. Please include the message id if one is provided.
        at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.run(DataflowPipelineRunner.java:399)
        at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.run(DataflowPipelineRunner.java:125)
        at com.google.cloud.dataflow.sdk.Pipeline.run(Pipeline.java:174)
        at com.semsiv.Start.main(Start.java:160)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "(1b9bcb283154c189): The workflow could not be created. Please try again in a few minutes. If you are still unable to create a job please contact customer support. Causes: (1b9bcb283154cdb2): An internal service error occurred. Please contact customer support. Please include the message id if one is provided.",
    "reason" : "badRequest"
  } ],
  "message" : "(1b9bcb283154c189): The workflow could not be created. Please try again in a few minutes. If you are still unable to create a job please contact customer support. Causes: (1b9bcb283154cdb2): An internal service error occurred. Please contact customer support. Please include the message id if one is provided.",
  "status" : "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.run(DataflowPipelineRunner.java:386)
        ... 3 more

**Comment by jkff** [comment]
Apologies for the delayed response. There is a bug in the Dataflow service that prevented us from showing you a detailed error message. Here is the real message: "Reserved worker memory allocation (3072 MB) exceeds machine capacity of 1740 MB" - can you give more details on what machine type you were using, and whether you were configuring any memory-related parameters for this job?

**Comment by albertog** [comment]
Now it is works

thnks
