### ISSUE TITLE
Can't run pipelines locally with Maven

### ISSUE THREAD

**Issue by layoaster** [GoogleCloudPlatform/DataflowJavaSDK#313]
Can't run any [official example](https://github.com/GoogleCloudPlatform/DataflowJavaSDK-examples) with the `DirectPipelineRunner`. Always get the same stacktrace:

`java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1234)
        at java.util.regex.Matcher.reset(Matcher.java:308)
        at java.util.regex.Matcher.<init>(Matcher.java:228)
        at java.util.regex.Pattern.matcher(Pattern.java:1088)
        at com.google.cloud.dataflow.sdk.util.IOChannelUtils.getFactory(IOChannelUtils.java:174)
        at com.google.cloud.dataflow.sdk.io.BigQueryIO$Read$Bound.apply(BigQueryIO.java:553)
        at com.google.cloud.dataflow.sdk.io.BigQueryIO$Read$Bound.apply(BigQueryIO.java:387)
        at com.google.cloud.dataflow.sdk.runners.PipelineRunner.apply(PipelineRunner.java:74)
        at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner.apply(DirectPipelineRunner.java:247)
        at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:367)
        at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:274)
        at com.google.cloud.dataflow.sdk.values.PBegin.apply(PBegin.java:47)
        at com.google.cloud.dataflow.sdk.Pipeline.apply(Pipeline.java:156)
        at com.google.cloud.dataflow.examples.cookbook.BigQueryTornadoes.main(BigQueryTornadoes.java:169)`

Execution command for [BigQueryTornadoes](https://github.com/GoogleCloudPlatform/DataflowJavaSDK-examples/blob/master/src/main/java/com/google/cloud/dataflow/examples/cookbook/BigQueryTornadoes.java):
`mvn compile exec:java \
-Dexec.mainClass=com.google.cloud.dataflow.examples.cookbook.BigQueryTornadoes \
-Dexec.args="--project=<project-id> \
--output=<project_id>:<dataset-id>.<table_id>"`

**Comment by lukecwik** [comment]
In newer versions of Dataflow, we have migrated to using an exporting the data from BigQuery to GCS as we have found that it performs much better and gives a stable snapshot of the data. When this change occurred, it seems as though we missed updating documentation specifying that you need to specify --tempLocation for some of the examples.

Note that --tempLocation will have to be a valid GCS bucket.

**Comment by layoaster** [comment]
Thanks for clarification. I got it working. Wouldn't make sense to show a more intuitive error message when `tempLocation` and `stagingLocation` aren't specified?

**Comment by lukecwik** [comment]
Yes, we should provide better error messaging.

I don't think you should need to specify `stagingLocation`.

**Comment by layoaster** [comment]
Indeed, there is no need but according to docs If `tempLocation` is not set, defaults to the value for `stagingLocation` so theoretically I could specify  stagingLocation instead and it should work.

**Comment by ravwojdyla** [comment]
@layoaster did you have problems similar to #330  ?
