### ISSUE TITLE
Local BigQueryIO obsolete/misleading export cleanup failures

### ISSUE THREAD

**Issue by ravwojdyla** [GoogleCloudPlatform/DataflowJavaSDK#330]
Some of the BigQuery GCS export logic was moved to SDK in `1.6.0`, afaiu local runners still use direct readers to read from BigQuery - more over `BigQueryIO.Bound.Read` will schedule `cleanupOperation` to clean up export data. The problem is that in case of local runners, there is no export job, thus cleanup will try `10` times (hard coded via `BigQueryServicesImpl.CLEANUP_JOB_POLL_MAX_RETRIES`) to check state of export job, each time failing (printing error messages [0]), and after some time (backoff algo) give up. There is not need to clean up data in local mode, thus cleanup operation is obsolete.

[0] export poll status error:

```
[run-main-0] WARN com.google.cloud.dataflow.sdk.util.BigQueryServicesImpl - Ignore the error and retry polling job status.
com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Not found: Job <project-id>:beam_job_435590fe990b45faaff7b18356cdca56-extract",
    "reason" : "notFound"
  } ],
  "message" : "Not found: Job <project-id>:beam_job_435590fe990b45faaff7b18356cdca56-extract"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.google.cloud.dataflow.sdk.util.BigQueryServicesImpl$JobServiceImpl.pollJob(BigQueryServicesImpl.java:214)
        at com.google.cloud.dataflow.sdk.util.BigQueryServicesImpl$JobServiceImpl.pollJob(BigQueryServicesImpl.java:204)
        at com.google.cloud.dataflow.sdk.io.BigQueryIO$Read$Bound$1.cleanup(BigQueryIO.java:587)
        at com.google.cloud.dataflow.sdk.io.BigQueryIO$PassThroughThenCleanup$1.processElement(BigQueryIO.java:722)
        at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:49)
        at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:138)
        at com.google.cloud.dataflow.sdk.transforms.ParDo.evaluateHelper(ParDo.java:1229)
        at com.google.cloud.dataflow.sdk.transforms.ParDo.evaluateSingleHelper(ParDo.java:1098)
        at com.google.cloud.dataflow.sdk.transforms.ParDo.access$300(ParDo.java:457)
        at com.google.cloud.dataflow.sdk.transforms.ParDo$1.evaluate(ParDo.java:1084)
        at com.google.cloud.dataflow.sdk.transforms.ParDo$1.evaluate(ParDo.java:1079)
        at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner$Evaluator.visitTransform(DirectPipelineRunner.java:858)
        at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:219)
        at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:215)
        at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:215)
        at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:215)
        at com.google.cloud.dataflow.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:102)
        at com.google.cloud.dataflow.sdk.Pipeline.traverseTopologically(Pipeline.java:259)
...
```

after 10 times, it gives up:

```
[run-main-0] WARN com.google.cloud.dataflow.sdk.util.BigQueryServicesImpl - Unable to poll job status: beam_job_435590fe990b45faaff7b18356cdca56-extract, aborting after reached max .
```

in the code it then tries to figure out the output files via `temp`/`staging` directory - again not needed for local runners.

One solution could be to figure out what mode BigQueryIO will running in and depending on the mode schedule cleanup or not. Another one could be to add option to BigQueryIO. Or maybe implement it as part of translation inside local pipeline runners. What do you think could be the best way to go?

**Comment by ravwojdyla** [comment]
I will go ahead na create a PR with extra method to check an existence of BQ job before polling for the result.
